### ISSUE TITLE
Transition to Micro

### ISSUE THREAD

**Issue by MAPESO** [zeit/hyper-site#21] opened 2018-04-16 18:08 UTC
To make the personalized routes we use express we can change it to ``micro.js``, it should not be so complicated to make this change 😸

**Comment by MAPESO** [comment] 2018-04-16 18:09
@timothyis If you want I can take care of that task 😸

**Comment by timneutkens** [comment] 2018-04-16 18:25
Duplicate of #20

**Closed by timneutkens** 2018-04-16 18:25 UTC
